server:
  port: ${PORT:8081}

spring:
  application:
    name: product-api
  main:
    allow-circular-references: true
  datasource:
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5433/product-db
      username: admin
      password: 123456
      initialization-mode: always
      initialize: true
      continue-on-error: true
      platform: postgresql
      maxActive: 10

  jpa:
    hibernate:
      ddl-auto: create-drop
      format_sql: true

    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

